### ISSUE TITLE
Crashes with illegal instruction on startup when rdrand is not supported by the cpu

### ISSUE THREAD

**Issue by symphorien** [RobJinman/pro_office_calc#5]
Hello
when I run procalc I get SIGILL on the instruction rdrand (which is not supported by my processor) at this location:
```
Program received signal SIGILL, Illegal instruction.
0x00007ffff5b2f1c5 in ?? () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
(gdb) where
#0  0x00007ffff5b2f1c5 in ?? () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
#1  0x00007ffff5b2f332 in std::random_device::_M_getval() () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
#2  0x0000000000514c10 in randomSeed() ()
#3  0x00000000004219d6 in _GLOBAL__sub_I_game_logic.cpp ()
#4  0x00000000005427ad in __libc_csu_init ()
#5  0x00007ffff4f11b1d in __libc_start_main () from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6
#6  0x0000000000423eaa in _start ()
```
I am no c++ guru, but here is my understanding of the situation.
`randomSeed` uses a `static random_device rd`. A debugger tels me that this static is not yet initialized
at the point of the crash (it is all zero). According to the backtrace, this is an instance of the static initialization order problem (https://isocpp.org/wiki/faq/ctors#static-init-order)
https://github.com/RobJinman/pro_office_calc/blob/307d02bf6f530e1cfcb3ea8ed202023dc3844255/src/fragments/f_main/f_app_dialog/f_server_room/game_logic.cpp#L21

randomSeed is called in a lot of places in a static constructor context, and at this point `rd` might not be initialized.
What happens then is that the only field of interest in a `random_device` is `_M_File` which is initialized by the constructor as follows:
* `NULL` if the processor supports rdrand
* an open file descriptor to `/dev/urandom` otherwise

In the case where `rd` is not initialized, then `_M_file` will be NULL and `rd()` will use the rdrand implementation.
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/src/c%2B%2B11/random.cc#L141-L142
When your cpu supports it, fine :) When it does not then you get a SIGILL.
I bet your cpu does support rdrand so you never have hit this problem.

This explanation is supported by the fact that this patch solves the problem:
```diff
diff --git a/src/utils.cpp b/src/utils.cpp
index 6783324..7b1172d 100644
--- a/src/utils.cpp
+++ b/src/utils.cpp
@@ -53,9 +53,8 @@ long randomSeed() {
   return duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
 }
 #else
-static std::random_device rd;
-
 long randomSeed() {
+  std::random_device rd;
   return rd();
 }
 #endif
```
even though it is suboptimal (it opens and closes `/dev/urandom` at each call of the function).

**Comment by symphorien** [comment]
Yes it works and opens /dev/urandom only 3 times instead of 12.
